# Yaml file pre-config for K-Infrastructure
#
## cd /etc/netplan/
## mv 00-installer-config.yaml 00-installer-config.yaml-back
## touch k-infra-ntk.yaml
## vim k-infra-ntk.yaml
#
#network:
#    ethernets:
#        eth0: - [ $name_interface ]
#            addresses: [192.168.1.200/24] - [ $addr_interface ]
#            gateway4: 192.168.1.1 - [ $addr_gateway ]
#            nameservers: - [ $declaration_dns ]
#                addresses: [8.8.8.8, 8.8.4.4] - [ $addr_dns ]
#            dhcp4: false - [ $status_dhcp4 ]
#            dhcp6: false - [ $status_dhcp6 ]
#    version: 2


# e.g.

network:
    ethernets:
        enp0s3:
            addresses: [192.168.50.0/24]
            gateway4: 192.168.50.1
            nameservers:
                addresses: [192.168.50.99, 192.168.50.1, 8.8.8.8, 1.1.1.1]
            dhcp4: false
            dhcp6: false
    version: 2